import { Product, Category } from "@/types";

const allProducts: Product[] = [
  {
    id: "polo-premium",
    name: "Camisa Gola Polo Premium",
    slug: "camisa-gola-polo-premium",
    description:
      "Camisa polo de alta qualidade em malha piquet, com corte moderno e acabamento premium. Ideal para qualquer ocasião, unindo elegância e conforto.",
    price: 84.90,
    originalPrice: 99.90,
    discount: 15,
    images: [
      "/images/roupas/camisas-polo/camisa-polo-1.png",
      "/images/roupas/camisas-polo/camisa-polo-2.png",
      "/images/roupas/camisas-polo/camisa-polo-3.png",
      "/images/roupas/camisas-polo/camisa-polo-4.png",
      "/images/roupas/camisas-polo/camisa-polo-5.png",
      "/images/roupas/camisas-polo/camisa-polo-6.png",
    ],
    category: "camisas",
    subcategory: "polo",
    brand: "Azevedo Ofts",
    tags: ["camisa polo", "polo", "casual", "premium"],
    color: "Preto, Branco, Musgo, Bege, Marrom",
    sizes: ["P", "M", "G", "GG", "XGG"],
    badge: "LANÇAMENTO",
    inStock: true,
    active: true,
    sold: 0,
    stock: 50,
    rating: 5.0,
    reviews: 0,
    collection: "Essenciais",
  },
  {
    id: "lacoste-casual",
    name: "Camisa Lacoste Casual",
    slug: "camisa-lacoste-casual",
    description: "Com design moderno e detalhes esportivos, a camiseta Lacoste une conforto, versatilidade e elegância, sendo ideal para composições casuais e sofisticadas.",
    price: 84.90,
    images: [
      "/images/roupas/camisas-casuais/camisa-lacoste-1.png",
      "/images/roupas/camisas-casuais/camisa-lacoste-2.jpeg",
      "/images/roupas/camisas-casuais/camisa-lacoste-3.jpeg",
    ],
    category: "camisas",
    subcategory: "casual",
    brand: "Lacoste",
    tags: ["lacoste", "casual", "minimalista"],
    color: "Preto, Branco, Off-white",
    sizes: ["M", "G", "GG"],
    badge: "LANÇAMENTO",
    inStock: true,
    active: true,
    sold: 0,
    stock: 50,
    rating: 5.0,
    reviews: 0,
    collection: "Casuais",
  },
  {
    id: "burberry-casual",
    name: "Camisa Burberry Casual",
    slug: "camisa-burberry-casual",
    description: "Com faixas contrastantes e visual contemporâneo, a camiseta Burberry oferece uma combinação de estilo, sofisticação e personalidade para o dia a dia.",
    price: 84.90,
    images: [
      "/images/roupas/camisas-casuais/camisa-burberry-1.png",
      "/images/roupas/camisas-casuais/camisa-burberry-2.jpeg",
    ],
    category: "camisas",
    subcategory: "casual",
    brand: "Burberry",
    tags: ["burberry", "casual", "moderna"],
    color: "Preto",
    sizes: ["M", "G", "GG"],
    badge: "LANÇAMENTO",
    inStock: true,
    active: true,
    sold: 0,
    stock: 50,
    rating: 5.0,
    reviews: 0,
    collection: "Casuais",
  },
  {
    id: "casablanca-estampada",
    name: "Camisa Casablanca Estampada",
    slug: "camisa-casablanca-estampada",
    description: "Com estampa gráfica exclusiva nas costas, detalhes coloridos e acabamento moderno, a camisa Casablanca combina personalidade, autenticidade e estilo urbano, destacando-se pela sua identidade visual marcante.",
    price: 84.90,
    images: [
      "/images/roupas/streetwear/camisa-casablanca-1.png",
      "/images/roupas/streetwear/camisa-casablanca-2.png",
      "/images/roupas/streetwear/camisa-casablanca-3.jpeg",
      "/images/roupas/streetwear/camisa-casablanca-4.jpeg",
    ],
    category: "camisas",
    subcategory: "streetwear",
    brand: "Casablanca",
    tags: ["streetwear", "urbano", "luxo"],
    color: "Preto, Branco",
    sizes: ["M", "G", "GG"],
    badge: "LANÇAMENTO",
    inStock: true,
    active: true,
    sold: 0,
    stock: 50,
    rating: 5.0,
    reviews: 0,
    collection: "Streetwear",
  },
  {
    id: "burberry-estampada",
    name: "Camisa Burberry Estampada",
    slug: "camisa-burberry-estampada",
    description: "Com estampa oversized em xadrez icônico, a camisa Burberry combina atitude urbana, personalidade e sofisticação. Seu design marcante proporciona um visual moderno e autêntico, ideal para composições streetwear.",
    price: 85.90,
    originalPrice: 95.44, // Calculated approx based on 10% discount
    discount: 10,
    images: [
      "/images/roupas/streetwear/camisa-burberry-1-1.png",
      "/images/roupas/streetwear/camisa-burberry-2-1.jpeg",
    ],
    category: "camisas",
    subcategory: "streetwear",
    brand: "Burberry",
    tags: ["burberry", "streetwear", "xadrez"],
    color: "Preto, Branco",
    sizes: ["M", "G", "GG"],
    badge: "LANÇAMENTO",
    inStock: true,
    active: true,
    sold: 0,
    stock: 50,
    rating: 5.0,
    reviews: 0,
    collection: "Streetwear",
  },
  {
    id: "armani-estampada",
    name: "Camisa EA7 Emporio Armani Estampada",
    slug: "camisa-armani-estampada",
    description: "Com estampa integral de logotipos EA7 em tons de preto e cinza, a camisa combina identidade esportiva, sofisticação e um visual urbano marcante, ideal para composições modernas e despojadas.",
    price: 84.90,
    originalPrice: 89.37, // Calculated approx based on 5% discount
    discount: 5,
    images: [
      "/images/roupas/streetwear/camisa-armani-1.png",
      "/images/roupas/streetwear/camisa-armani-2.jpeg",
      "/images/roupas/streetwear/camisa-armani-3.jpeg",
    ],
    category: "camisas",
    subcategory: "streetwear",
    brand: "EA7 Emporio Armani",
    tags: ["armani", "streetwear", "esportivo"],
    color: "Preto, Branco",
    sizes: ["M", "G", "GG"],
    badge: "LANÇAMENTO",
    inStock: true,
    active: true,
    sold: 0,
    stock: 50,
    rating: 5.0,
    reviews: 0,
    collection: "Streetwear",
  },
  {
    id: "lacoste-live",
    name: "Camisa Lacoste Live",
    slug: "camisa-lacoste-live",
    description: "Com design moderno, faixa diagonal em cinza e detalhes contrastantes, a camisa Lacoste Live combina personalidade, versatilidade e uma estética esportiva para composições casuais.",
    price: 84.90,
    images: [
      "/images/roupas/camisas-casuais/camisa-lacoste-1-1.png",
      "/images/roupas/camisas-casuais/camisa-lacoste-2-1.jpeg",
      "/images/roupas/camisas-casuais/camisa-lacoste-3-1.jpeg",
    ],
    category: "camisas",
    subcategory: "casual",
    brand: "Lacoste",
    tags: ["lacoste", "sport casual", "moderna"],
    color: "Preto, Branco, Off-white",
    sizes: ["M", "G", "GG"],
    badge: "LANÇAMENTO",
    inStock: true,
    active: true,
    sold: 0,
    stock: 50,
    rating: 5.0,
    reviews: 0,
    collection: "Casuais",
  },
  {
    id: "aleatory-polo",
    name: "Camisa Polo Aleatory Listrada",
    slug: "camisa-polo-aleatory-listrada",
    description: "Com listras diagonais em azul e branco, gola polo e textura diferenciada, a camisa Aleatory combina conforto, elegância e um visual esportivo moderno, ideal para ocasiões casuais.",
    price: 85.90,
    originalPrice: 104.57, // Calculated approx based on 18% discount
    discount: 18,
    images: [
      "/images/roupas/camisas-polo/camisa-aleatory-1.jpeg",
      "/images/roupas/camisas-polo/camisa-aleatory-2.jpeg",
    ],
    category: "camisas",
    subcategory: "polo",
    brand: "Aleatory",
    tags: ["polo", "listrada", "sport casual"],
    color: "Azul Marinho, Marrom, Preto, Azul Escuro, Vermelho, Azul Claro, Cinza",
    sizes: ["M", "G", "GG"],
    badge: "LANÇAMENTO",
    inStock: true,
    active: true,
    sold: 0,
    stock: 50,
    rating: 5.0,
    reviews: 0,
    collection: "Polos",
  },
  {
    id: "lacoste-live-estampada",
    name: "Camisa Lacoste Live Estampada",
    slug: "camisa-lacoste-live-estampada",
    description: "Com estampa frontal em destaque, detalhes em verde e design contemporâneo, a camisa Lacoste Live combina personalidade, autenticidade e sofisticação em uma proposta urbana e despojada.",
    price: 84.90,
    images: [
      "/images/roupas/streetwear/camisa-lacoste-1-3.png",
      "/images/roupas/streetwear/camisa-lacoste-2-3.jpeg",
    ],
    category: "camisas",
    subcategory: "streetwear",
    brand: "Lacoste",
    tags: ["lacoste", "streetwear", "estampada"],
    color: "Preto",
    sizes: ["M", "G", "GG"],
    badge: "LANÇAMENTO",
    inStock: true,
    active: true,
    sold: 0,
    stock: 50,
    rating: 5.0,
    reviews: 0,
    collection: "Streetwear",
  },
  {
    id: "brooksfield-polo",
    name: "Camisa Polo Brooksfield Listrada",
    slug: "camisa-polo-brooksfield-listrada",
    description: "Com listras diagonais em azul-marinho e branco, textura diferenciada e bordado discreto, a camisa polo Brooksfield combina elegância, conforto e um visual moderno, ideal para composições casuais sofisticadas.",
    price: 85.90,
    originalPrice: 102.59, // Calculated approx based on 16% discount
    discount: 16,
    images: [
      "/images/roupas/camisas-polo/camisa-brooksfield-1.jpeg",
      "/images/roupas/camisas-polo/camisa-brooksfield-2.jpeg",
    ],
    category: "camisas",
    subcategory: "polo",
    brand: "Brooksfield",
    tags: ["polo", "listrada", "sport casual"],
    color: "Azul Marinho, Marrom, Preto, Azul Escuro, Vermelho, Azul Claro, Cinza",
    sizes: ["M", "G", "GG"],
    badge: "LANÇAMENTO",
    inStock: true,
    active: true,
    sold: 0,
    stock: 50,
    rating: 5.0,
    reviews: 0,
    collection: "Polos",
  },
  {
    id: "bermuda-sport-jordan",
    name: "Bermuda Sport Jordan",
    slug: "bermuda-sport-jordan",
    description:
      "Bermuda Sport Jordan com visual esportivo e confortável. Disponível em diferentes combinações de cores e nos tamanhos M, G e GG.",
    price: 95,
    originalPrice: 111.76,
    discount: 15,
    images: [
      "/images/roupas/bermudas/sport/bermuda-jordan-1.jpeg",
      "/images/roupas/bermudas/sport/bermuda-jordan-2.jpeg",
      "/images/roupas/bermudas/sport/bermuda-jordan-3.jpeg",
      "/images/roupas/bermudas/sport/bermuda-jordan-4.jpeg",
      "/images/roupas/bermudas/sport/bermuda-jordan-5.jpeg",
      "/images/roupas/bermudas/sport/bermuda-jordan-6.jpeg",
    ],
    category: "bermudas",
    subcategory: "sport",
    brand: "Jordan",
    tags: ["bermuda", "sport", "jordan", "esportiva", "promoção"],
    color:
      "Preto com branco, Azul-marinho com branco, Vermelho com preto, Branco com preto, Bege com branco, Verde com branco, Preto com azul, Estampados e outras combinações de cores",
    sizes: ["M", "G", "GG"],
    badge: null,
    inStock: true,
    active: true,
    sold: 0,
    stock: 50,
    rating: 5.0,
    reviews: 0,
  },
];

// Produtos ativos exibidos na loja
export const products: Product[] = allProducts.filter((p) => p.active !== false);

export const categories: Category[] = [
  {
    name: "Camisas",
    slug: "camisas",
    icon: "Shirt",
    image: "/images/categorias/img-categorias-camisa.png",
    subcategories: [
      { name: "Camisas Polo", slug: "polo" },
      { name: "Camisas Casuais", slug: "casual" },
      { name: "Streetwear", slug: "streetwear" },
    ],
  },
  {
    name: "Conjuntos",
    slug: "conjuntos",
    icon: "Package",
    image: "/images/categorias/img-categorias-conjuntos.png",
    subcategories: [],
  },
  {
    name: "Calças",
    slug: "calcas",
    icon: "RectangleVertical",
    image: "/images/categorias/img-categorias-calca.png",
    subcategories: [],
  },
  {
    name: "Bermudas",
    slug: "bermudas",
    icon: "Layers",
    image: "/images/categorias/img-categorias-bermuda.png",
    subcategories: [{ name: "Sport", slug: "sport" }],
  },
  {
    name: "Bonés",
    slug: "bones",
    icon: "HardHat",
    image: "/images/categorias/img-categorias-boné.png",
    subcategories: [],
  },
];
